### ISSUE TITLE
JS error after click import demo

### ISSUE THREAD

**Issue by MrAndreius** [richtabor/MerlinWP#45] opened 2018-02-16 20:06 UTC
`merlin.js:351 Uncaught TypeError: Cannot read property 'toLowerCase' of null
    at Object.ajax_callback [as success] (merlin.js:351)
    at i (load-scripts.php:2)
    at Object.fireWith [as resolveWith] (load-scripts.php:2)
    at y (load-scripts.php:4)
    at XMLHttpRequest.c (load-scripts.php:4)`

**Comment by capuderg** [comment] 2018-02-26 12:40
Hi @MrAndreius,

I can't reproduce this issue on my end. Could you please try this with a fresh installation of WP Merlin and let me know, if this is still a problem.

Also some more details to the problem would be welcome. How to reproduce it by steps, maybe share the merlin config file?

Take care!

**Comment by richtabor** [comment] 2018-02-28 18:40
I had this error once as well, but it was because my content files were not resolving properly. Mind double-checking that yours are? 👍

**Closed** 2018-03-03 01:49 UTC
Labels: invalid
